name: Deploy CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-node@v2
      with:
        node-version: '11.10.1'

    - name: Install 🔧
      run: |
        npm install
        gulp build

    - name: Build and Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: .
